LISTEN_ADDRESS: "0.0.0.0"
LISTEN_PORT: "8000"
DEVELOPMENT: "1"

FIXTURES_TO_UPLOAD:
  - "openstack_folsom.json"

DATABASE_ENGINE: "sqlite:////var/tmp/nailgun.sqlite"
STATIC_DIR: "/var/tmp/nailgun_static"
TEMPLATE_DIR: "/var/tmp/nailgun_static"
NETWORK_POOLS:
  public:
    - "240.0.0.0/16"
  private10:
    - "10.0.0.0/8"
  private172:
    - "172.16.0.0/12"
  private192:
    - "192.168.0.0/16"

NET_EXCLUDE:
  - "10.20.0.0/24"

VLANS_RANGE_START: "100"
VLANS_RANGE_END: "1000"

RABBITMQ:
  fake: "0"
  hostname: "127.0.0.1"

CUSTOM_LOG: &nailgun_log "/var/log/nailgun.log"
ACCESS_LOG: "/var/log/nailgun_access.log"

PATH_TO_SSH_KEY: = "/root/.ssh/id_rsa"
PATH_TO_BOOTSTRAP_SSH_KEY: "/root/.ssh/bootstrap.rsa"

COBBLER_URL: "http://localhost/cobbler_api"
COBBLER_USER: "cobbler"
COBBLER_PASSWORD: "cobbler"
COBBLER_PROFILE: "centos63-x86_64"

LOG_TYPES:
  - &local
    remote: False
    regexp: '^(?P<date>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2},\d{3})\s(?P<level>[A-Z]+)\s(?P<text>.*)$'
  - &remote
    remote: True
    regexp: '^(?P<ip>\d+\.\d+\.\d+\.\d+)\s+(?P<date>\w{3}\s+\d+\s+\d+:\d+:\d+)\s+(?P<fqdn>[\w\.\-]+)\s+(?P<component>[\w\.\-/]+):\s+(?:[\d:,]+\s+(?P<level>[A-Z]+)\s+)?(?:\s*:\s*)?(?P<text>.*)$'
    base: '/var/log/remote/'
LOGS:
  - id: nailgun
    name: "Nailgun"
    <<: *local
    path: *nailgun_log
  - id: syslog
    name: "Syslog"
    <<: *remote
    path: 'install/syslog.log'
  - id: storage
    name: "Storage"
    <<: *remote
    path: 'install/storage.log'

MCO_PSKEY: "Gie6iega9ohngaenahthohngu8aebohxah9seidi"
MCO_STOMPHOST: "localhost"
MCO_STOMPPORT: "61613"
MCO_STOMPUSER: "guest"
MCO_STOMPPASSWORD: "guest"

PUPPET_MASTER_HOST: "localhost"
PUPPET_VERSION: "2.7.19"

DNS_DOMAIN: "example.com"
DNS_SERVERS: "127.0.0.1"
DNS_SEARCH: "example.com"

